// Static dataset of major Indian pincodes
const PINCODES = {
  // Mumbai
  '400001': { area: 'Fort', city: 'Mumbai', state: 'Maharashtra' },
  '400002': { area: 'Mandvi', city: 'Mumbai', state: 'Maharashtra' },
  '400003': { area: 'Masjid Bunder', city: 'Mumbai', state: 'Maharashtra' },
  '400004': { area: 'Girgaon', city: 'Mumbai', state: 'Maharashtra' },
  '400005': { area: 'Colaba', city: 'Mumbai', state: 'Maharashtra' },
  '400006': { area: 'Malabar Hill', city: 'Mumbai', state: 'Maharashtra' },
  '400007': { area: 'Grant Road', city: 'Mumbai', state: 'Maharashtra' },
  '400008': { area: 'Mumbai Central', city: 'Mumbai', state: 'Maharashtra' },
  '400009': { area: 'Mazgaon', city: 'Mumbai', state: 'Maharashtra' },
  '400010': { area: 'Byculla', city: 'Mumbai', state: 'Maharashtra' },
  '400011': { area: 'Lalbaug', city: 'Mumbai', state: 'Maharashtra' },
  '400012': { area: 'Parel', city: 'Mumbai', state: 'Maharashtra' },
  '400013': { area: 'Dadar', city: 'Mumbai', state: 'Maharashtra' },
  '400014': { area: 'Dadar East', city: 'Mumbai', state: 'Maharashtra' },
  '400016': { area: 'Mahim', city: 'Mumbai', state: 'Maharashtra' },
  '400017': { area: 'Dharavi', city: 'Mumbai', state: 'Maharashtra' },
  '400018': { area: 'Worli', city: 'Mumbai', state: 'Maharashtra' },
  '400019': { area: 'Sion', city: 'Mumbai', state: 'Maharashtra' },
  '400020': { area: 'Churchgate', city: 'Mumbai', state: 'Maharashtra' },
  '400021': { area: 'Nariman Point', city: 'Mumbai', state: 'Maharashtra' },
  '400022': { area: 'Chembur', city: 'Mumbai', state: 'Maharashtra' },
  '400025': { area: 'Prabhadevi', city: 'Mumbai', state: 'Maharashtra' },
  '400028': { area: 'Matunga', city: 'Mumbai', state: 'Maharashtra' },
  '400029': { area: 'Wadala', city: 'Mumbai', state: 'Maharashtra' },
  '400030': { area: 'Sewri', city: 'Mumbai', state: 'Maharashtra' },
  '400031': { area: 'Lower Parel', city: 'Mumbai', state: 'Maharashtra' },
  '400034': { area: 'Santacruz West', city: 'Mumbai', state: 'Maharashtra' },
  '400049': { area: 'Juhu', city: 'Mumbai', state: 'Maharashtra' },
  '400050': { area: 'Bandra West', city: 'Mumbai', state: 'Maharashtra' },
  '400051': { area: 'Bandra East', city: 'Mumbai', state: 'Maharashtra' },
  '400052': { area: 'Khar', city: 'Mumbai', state: 'Maharashtra' },
  '400053': { area: 'Andheri West', city: 'Mumbai', state: 'Maharashtra' },
  '400054': { area: 'Vile Parle', city: 'Mumbai', state: 'Maharashtra' },
  '400055': { area: 'Santacruz East', city: 'Mumbai', state: 'Maharashtra' },
  '400057': { area: 'Andheri East', city: 'Mumbai', state: 'Maharashtra' },
  '400058': { area: 'Jogeshwari', city: 'Mumbai', state: 'Maharashtra' },
  '400059': { area: 'Malad West', city: 'Mumbai', state: 'Maharashtra' },
  '400060': { area: 'Malad East', city: 'Mumbai', state: 'Maharashtra' },
  '400061': { area: 'Goregaon', city: 'Mumbai', state: 'Maharashtra' },
  '400062': { area: 'Kandivali', city: 'Mumbai', state: 'Maharashtra' },
  '400063': { area: 'Borivali West', city: 'Mumbai', state: 'Maharashtra' },
  '400064': { area: 'Borivali East', city: 'Mumbai', state: 'Maharashtra' },
  '400068': { area: 'Ghatkopar', city: 'Mumbai', state: 'Maharashtra' },
  '400069': { area: 'Vikhroli', city: 'Mumbai', state: 'Maharashtra' },
  '400070': { area: 'Kurla', city: 'Mumbai', state: 'Maharashtra' },
  '400071': { area: 'Chembur East', city: 'Mumbai', state: 'Maharashtra' },
  '400072': { area: 'Govandi', city: 'Mumbai', state: 'Maharashtra' },
  '400074': { area: 'Mulund West', city: 'Mumbai', state: 'Maharashtra' },
  '400075': { area: 'Bhandup', city: 'Mumbai', state: 'Maharashtra' },
  '400076': { area: 'Powai', city: 'Mumbai', state: 'Maharashtra' },
  '400077': { area: 'Vikhroli East', city: 'Mumbai', state: 'Maharashtra' },
  '400078': { area: 'Kanjurmarg', city: 'Mumbai', state: 'Maharashtra' },
  '400080': { area: 'Mulund East', city: 'Mumbai', state: 'Maharashtra' },
  '400086': { area: 'Dahisar', city: 'Mumbai', state: 'Maharashtra' },
  '400097': { area: 'Magathane', city: 'Mumbai', state: 'Maharashtra' },
  '400101': { area: 'Mira Road', city: 'Thane', state: 'Maharashtra' },
  '400601': { area: 'Thane West', city: 'Thane', state: 'Maharashtra' },
  '400602': { area: 'Thane East', city: 'Thane', state: 'Maharashtra' },
  '400604': { area: 'Ghodbunder Road', city: 'Thane', state: 'Maharashtra' },
  '400701': { area: 'Belapur', city: 'Navi Mumbai', state: 'Maharashtra' },
  '400703': { area: 'Airoli', city: 'Navi Mumbai', state: 'Maharashtra' },
  '400706': { area: 'Kharghar', city: 'Navi Mumbai', state: 'Maharashtra' },
  '400708': { area: 'Panvel', city: 'Navi Mumbai', state: 'Maharashtra' },
  '400709': { area: 'Nerul', city: 'Navi Mumbai', state: 'Maharashtra' },
  '400710': { area: 'Vashi', city: 'Navi Mumbai', state: 'Maharashtra' },

  // Delhi
  '110001': { area: 'Connaught Place', city: 'New Delhi', state: 'Delhi' },
  '110002': { area: 'Daryaganj', city: 'New Delhi', state: 'Delhi' },
  '110003': { area: 'Lodi Road', city: 'New Delhi', state: 'Delhi' },
  '110004': { area: 'Raj Ghat', city: 'New Delhi', state: 'Delhi' },
  '110005': { area: 'Karol Bagh', city: 'New Delhi', state: 'Delhi' },
  '110006': { area: 'Sadar Bazar', city: 'New Delhi', state: 'Delhi' },
  '110007': { area: 'Patel Nagar', city: 'New Delhi', state: 'Delhi' },
  '110008': { area: 'Kirti Nagar', city: 'New Delhi', state: 'Delhi' },
  '110009': { area: 'Inderpuri', city: 'New Delhi', state: 'Delhi' },
  '110010': { area: 'Lajpat Nagar', city: 'New Delhi', state: 'Delhi' },
  '110011': { area: 'Safdarjung', city: 'New Delhi', state: 'Delhi' },
  '110012': { area: 'Anand Niketan', city: 'New Delhi', state: 'Delhi' },
  '110013': { area: 'Okhla', city: 'New Delhi', state: 'Delhi' },
  '110014': { area: 'Jangpura', city: 'New Delhi', state: 'Delhi' },
  '110015': { area: 'Tilak Nagar', city: 'New Delhi', state: 'Delhi' },
  '110016': { area: 'Hauz Khas', city: 'New Delhi', state: 'Delhi' },
  '110017': { area: 'Saket', city: 'New Delhi', state: 'Delhi' },
  '110018': { area: 'Janakpuri', city: 'New Delhi', state: 'Delhi' },
  '110019': { area: 'Kalkaji', city: 'New Delhi', state: 'Delhi' },
  '110020': { area: 'Vasant Kunj', city: 'New Delhi', state: 'Delhi' },
  '110021': { area: 'Dwarka', city: 'New Delhi', state: 'Delhi' },
  '110022': { area: 'Malviya Nagar', city: 'New Delhi', state: 'Delhi' },
  '110023': { area: 'Mehrauli', city: 'New Delhi', state: 'Delhi' },
  '110024': { area: 'Lajpat Nagar II', city: 'New Delhi', state: 'Delhi' },
  '110025': { area: 'Trilokpuri', city: 'New Delhi', state: 'Delhi' },
  '110026': { area: 'Rohini', city: 'New Delhi', state: 'Delhi' },
  '110027': { area: 'Moti Nagar', city: 'New Delhi', state: 'Delhi' },
  '110028': { area: 'Rajouri Garden', city: 'New Delhi', state: 'Delhi' },
  '110029': { area: 'Green Park', city: 'New Delhi', state: 'Delhi' },
  '110030': { area: 'Vasant Vihar', city: 'New Delhi', state: 'Delhi' },
  '110034': { area: 'Pitampura', city: 'New Delhi', state: 'Delhi' },
  '110044': { area: 'Shahdara', city: 'New Delhi', state: 'Delhi' },
  '110045': { area: 'Uttam Nagar', city: 'New Delhi', state: 'Delhi' },
  '110054': { area: 'Civil Lines', city: 'New Delhi', state: 'Delhi' },
  '110063': { area: 'Paschim Vihar', city: 'New Delhi', state: 'Delhi' },
  '110075': { area: 'Dwarka Sector 10', city: 'New Delhi', state: 'Delhi' },
  '110091': { area: 'Mayur Vihar', city: 'New Delhi', state: 'Delhi' },
  '110092': { area: 'Preet Vihar', city: 'New Delhi', state: 'Delhi' },
  '110096': { area: 'Patparganj', city: 'New Delhi', state: 'Delhi' },

  // Bangalore
  '560001': { area: 'MG Road', city: 'Bangalore', state: 'Karnataka' },
  '560002': { area: 'Shivajinagar', city: 'Bangalore', state: 'Karnataka' },
  '560003': { area: 'Rajajinagar', city: 'Bangalore', state: 'Karnataka' },
  '560004': { area: 'Sadashivanagar', city: 'Bangalore', state: 'Karnataka' },
  '560005': { area: 'Malleswaram', city: 'Bangalore', state: 'Karnataka' },
  '560008': { area: 'Vasanthnagar', city: 'Bangalore', state: 'Karnataka' },
  '560010': { area: 'Jayanagar', city: 'Bangalore', state: 'Karnataka' },
  '560011': { area: 'Basavanagudi', city: 'Bangalore', state: 'Karnataka' },
  '560017': { area: 'Vijayanagar', city: 'Bangalore', state: 'Karnataka' },
  '560020': { area: 'Banashankari', city: 'Bangalore', state: 'Karnataka' },
  '560025': { area: 'Wilson Garden', city: 'Bangalore', state: 'Karnataka' },
  '560027': { area: 'Yeshwanthpur', city: 'Bangalore', state: 'Karnataka' },
  '560029': { area: 'Hebbal', city: 'Bangalore', state: 'Karnataka' },
  '560032': { area: 'New BEL Road', city: 'Bangalore', state: 'Karnataka' },
  '560034': { area: 'Koramangala', city: 'Bangalore', state: 'Karnataka' },
  '560037': { area: 'HBR Layout', city: 'Bangalore', state: 'Karnataka' },
  '560038': { area: 'Indiranagar', city: 'Bangalore', state: 'Karnataka' },
  '560040': { area: 'Nagarbhavi', city: 'Bangalore', state: 'Karnataka' },
  '560041': { area: 'Padmanabhanagar', city: 'Bangalore', state: 'Karnataka' },
  '560043': { area: 'JP Nagar', city: 'Bangalore', state: 'Karnataka' },
  '560045': { area: 'Marathahalli', city: 'Bangalore', state: 'Karnataka' },
  '560047': { area: 'Ulsoor', city: 'Bangalore', state: 'Karnataka' },
  '560048': { area: 'Ramamurthy Nagar', city: 'Bangalore', state: 'Karnataka' },
  '560050': { area: 'Lingarajapuram', city: 'Bangalore', state: 'Karnataka' },
  '560052': { area: 'Kammanahalli', city: 'Bangalore', state: 'Karnataka' },
  '560054': { area: 'Nagawara', city: 'Bangalore', state: 'Karnataka' },
  '560060': { area: 'Electronic City', city: 'Bangalore', state: 'Karnataka' },
  '560066': { area: 'Whitefield', city: 'Bangalore', state: 'Karnataka' },
  '560068': { area: 'HAL', city: 'Bangalore', state: 'Karnataka' },
  '560076': { area: 'BTM Layout', city: 'Bangalore', state: 'Karnataka' },
  '560085': { area: 'Hennur', city: 'Bangalore', state: 'Karnataka' },
  '560086': { area: 'Brookefield', city: 'Bangalore', state: 'Karnataka' },
  '560093': { area: 'Begur', city: 'Bangalore', state: 'Karnataka' },
  '560095': { area: 'Kengeri', city: 'Bangalore', state: 'Karnataka' },
  '560097': { area: 'Bannerghatta Road', city: 'Bangalore', state: 'Karnataka' },
  '560100': { area: 'Sarjapur Road', city: 'Bangalore', state: 'Karnataka' },
  '560102': { area: 'HSR Layout', city: 'Bangalore', state: 'Karnataka' },
  '560103': { area: 'Bellandur', city: 'Bangalore', state: 'Karnataka' },

  // Hyderabad
  '500001': { area: 'Abids', city: 'Hyderabad', state: 'Telangana' },
  '500002': { area: 'Nampally', city: 'Hyderabad', state: 'Telangana' },
  '500003': { area: 'Secunderabad', city: 'Hyderabad', state: 'Telangana' },
  '500004': { area: 'Trimulgherry', city: 'Hyderabad', state: 'Telangana' },
  '500007': { area: 'Ameerpet', city: 'Hyderabad', state: 'Telangana' },
  '500008': { area: 'Begumpet', city: 'Hyderabad', state: 'Telangana' },
  '500016': { area: 'SR Nagar', city: 'Hyderabad', state: 'Telangana' },
  '500018': { area: 'Kukatpally', city: 'Hyderabad', state: 'Telangana' },
  '500019': { area: 'KPHB Colony', city: 'Hyderabad', state: 'Telangana' },
  '500020': { area: 'Somajiguda', city: 'Hyderabad', state: 'Telangana' },
  '500026': { area: 'Banjara Hills Road 1', city: 'Hyderabad', state: 'Telangana' },
  '500033': { area: 'Jubilee Hills', city: 'Hyderabad', state: 'Telangana' },
  '500034': { area: 'Banjara Hills', city: 'Hyderabad', state: 'Telangana' },
  '500038': { area: 'LB Nagar', city: 'Hyderabad', state: 'Telangana' },
  '500049': { area: 'Malkajgiri', city: 'Hyderabad', state: 'Telangana' },
  '500050': { area: 'Dilsukhnagar', city: 'Hyderabad', state: 'Telangana' },
  '500055': { area: 'Gachibowli', city: 'Hyderabad', state: 'Telangana' },
  '500072': { area: 'Alwal', city: 'Hyderabad', state: 'Telangana' },
  '500081': { area: 'Hitech City', city: 'Hyderabad', state: 'Telangana' },
  '500082': { area: 'Madhapur', city: 'Hyderabad', state: 'Telangana' },
  '500084': { area: 'Kondapur', city: 'Hyderabad', state: 'Telangana' },
  '500089': { area: 'Miyapur', city: 'Hyderabad', state: 'Telangana' },
  '500090': { area: 'Bachupally', city: 'Hyderabad', state: 'Telangana' },

  // Chennai
  '600001': { area: 'Chennai GPO', city: 'Chennai', state: 'Tamil Nadu' },
  '600002': { area: 'Park Town', city: 'Chennai', state: 'Tamil Nadu' },
  '600003': { area: 'Triplicane', city: 'Chennai', state: 'Tamil Nadu' },
  '600004': { area: 'Chintadripet', city: 'Chennai', state: 'Tamil Nadu' },
  '600005': { area: 'Royapuram', city: 'Chennai', state: 'Tamil Nadu' },
  '600006': { area: 'Egmore', city: 'Chennai', state: 'Tamil Nadu' },
  '600007': { area: 'Vepery', city: 'Chennai', state: 'Tamil Nadu' },
  '600008': { area: 'Chepauk', city: 'Chennai', state: 'Tamil Nadu' },
  '600010': { area: 'Perambur', city: 'Chennai', state: 'Tamil Nadu' },
  '600011': { area: 'Royapettah', city: 'Chennai', state: 'Tamil Nadu' },
  '600014': { area: 'Chetpet', city: 'Chennai', state: 'Tamil Nadu' },
  '600017': { area: 'T Nagar', city: 'Chennai', state: 'Tamil Nadu' },
  '600018': { area: 'Kodambakkam', city: 'Chennai', state: 'Tamil Nadu' },
  '600020': { area: 'Saidapet', city: 'Chennai', state: 'Tamil Nadu' },
  '600024': { area: 'Mylapore', city: 'Chennai', state: 'Tamil Nadu' },
  '600025': { area: 'Adyar', city: 'Chennai', state: 'Tamil Nadu' },
  '600026': { area: 'Mandaveli', city: 'Chennai', state: 'Tamil Nadu' },
  '600028': { area: 'Nungambakkam', city: 'Chennai', state: 'Tamil Nadu' },
  '600029': { area: 'Kilpauk', city: 'Chennai', state: 'Tamil Nadu' },
  '600030': { area: 'Aminjikarai', city: 'Chennai', state: 'Tamil Nadu' },
  '600031': { area: 'Anna Nagar West', city: 'Chennai', state: 'Tamil Nadu' },
  '600035': { area: 'Arumbakkam', city: 'Chennai', state: 'Tamil Nadu' },
  '600040': { area: 'Anna Nagar', city: 'Chennai', state: 'Tamil Nadu' },
  '600041': { area: 'Mogappair', city: 'Chennai', state: 'Tamil Nadu' },
  '600042': { area: 'Velachery', city: 'Chennai', state: 'Tamil Nadu' },
  '600045': { area: 'Pallikaranai', city: 'Chennai', state: 'Tamil Nadu' },
  '600053': { area: 'Ashok Nagar', city: 'Chennai', state: 'Tamil Nadu' },
  '600078': { area: 'Virugambakkam', city: 'Chennai', state: 'Tamil Nadu' },
  '600083': { area: 'Ambattur', city: 'Chennai', state: 'Tamil Nadu' },
  '600087': { area: 'Sholinganallur', city: 'Chennai', state: 'Tamil Nadu' },
  '600096': { area: 'Porur', city: 'Chennai', state: 'Tamil Nadu' },
  '600097': { area: 'Madipakkam', city: 'Chennai', state: 'Tamil Nadu' },
  '600100': { area: 'Chromepet', city: 'Chennai', state: 'Tamil Nadu' },
  '600116': { area: 'Perungudi', city: 'Chennai', state: 'Tamil Nadu' },
  '600119': { area: 'OMR Thoraipakkam', city: 'Chennai', state: 'Tamil Nadu' },

  // Kolkata
  '700001': { area: 'BBD Bagh', city: 'Kolkata', state: 'West Bengal' },
  '700002': { area: 'Shyambazar', city: 'Kolkata', state: 'West Bengal' },
  '700003': { area: 'Maniktala', city: 'Kolkata', state: 'West Bengal' },
  '700004': { area: 'Entally', city: 'Kolkata', state: 'West Bengal' },
  '700005': { area: 'Burtolla', city: 'Kolkata', state: 'West Bengal' },
  '700006': { area: 'Hatibagan', city: 'Kolkata', state: 'West Bengal' },
  '700007': { area: 'Ultadanga', city: 'Kolkata', state: 'West Bengal' },
  '700008': { area: 'Cossipore', city: 'Kolkata', state: 'West Bengal' },
  '700009': { area: 'Baghbazar', city: 'Kolkata', state: 'West Bengal' },
  '700010': { area: 'Ballygunge', city: 'Kolkata', state: 'West Bengal' },
  '700012': { area: 'Bhowanipore', city: 'Kolkata', state: 'West Bengal' },
  '700013': { area: 'Watgunge', city: 'Kolkata', state: 'West Bengal' },
  '700014': { area: 'Garden Reach', city: 'Kolkata', state: 'West Bengal' },
  '700015': { area: 'Kalighat', city: 'Kolkata', state: 'West Bengal' },
  '700016': { area: 'Park Street', city: 'Kolkata', state: 'West Bengal' },
  '700017': { area: 'Lansdowne', city: 'Kolkata', state: 'West Bengal' },
  '700018': { area: 'Rashbehari', city: 'Kolkata', state: 'West Bengal' },
  '700019': { area: 'Ballygunge Place', city: 'Kolkata', state: 'West Bengal' },
  '700020': { area: 'Alipore', city: 'Kolkata', state: 'West Bengal' },
  '700026': { area: 'Chowringhee', city: 'Kolkata', state: 'West Bengal' },
  '700027': { area: 'Beckbagan', city: 'Kolkata', state: 'West Bengal' },
  '700028': { area: 'Karaya', city: 'Kolkata', state: 'West Bengal' },
  '700029': { area: 'Jadavpur', city: 'Kolkata', state: 'West Bengal' },
  '700030': { area: 'Tollygunge', city: 'Kolkata', state: 'West Bengal' },
  '700031': { area: 'Behala', city: 'Kolkata', state: 'West Bengal' },
  '700032': { area: 'Thakurpukur', city: 'Kolkata', state: 'West Bengal' },
  '700033': { area: 'Joka', city: 'Kolkata', state: 'West Bengal' },
  '700034': { area: 'Metiabruz', city: 'Kolkata', state: 'West Bengal' },
  '700036': { area: 'Manicktala', city: 'Kolkata', state: 'West Bengal' },
  '700039': { area: 'Dhakuria', city: 'Kolkata', state: 'West Bengal' },
  '700041': { area: 'Lake Gardens', city: 'Kolkata', state: 'West Bengal' },
  '700045': { area: 'Garia', city: 'Kolkata', state: 'West Bengal' },
  '700046': { area: 'Santoshpur', city: 'Kolkata', state: 'West Bengal' },
  '700048': { area: 'Kasba', city: 'Kolkata', state: 'West Bengal' },
  '700053': { area: 'Dum Dum', city: 'Kolkata', state: 'West Bengal' },
  '700054': { area: 'Belgharia', city: 'Kolkata', state: 'West Bengal' },
  '700059': { area: 'Sodepur', city: 'Kolkata', state: 'West Bengal' },
  '700060': { area: 'Panihati', city: 'Kolkata', state: 'West Bengal' },
  '700063': { area: 'New Alipore', city: 'Kolkata', state: 'West Bengal' },
  '700064': { area: 'Regent Park', city: 'Kolkata', state: 'West Bengal' },
  '700075': { area: 'Bansdroni', city: 'Kolkata', state: 'West Bengal' },
  '700080': { area: 'Anandapur', city: 'Kolkata', state: 'West Bengal' },
  '700086': { area: 'Patuli', city: 'Kolkata', state: 'West Bengal' },
  '700091': { area: 'Salt Lake City', city: 'Kolkata', state: 'West Bengal' },
  '700094': { area: 'Gariahat', city: 'Kolkata', state: 'West Bengal' },
  '700095': { area: 'Narendrapur', city: 'Kolkata', state: 'West Bengal' },
  '700096': { area: 'Sonarpur', city: 'Kolkata', state: 'West Bengal' },
  '700099': { area: 'Barasat', city: 'Kolkata', state: 'West Bengal' },
  '700101': { area: 'Rajarhat', city: 'Kolkata', state: 'West Bengal' },
  '700102': { area: 'New Town', city: 'Kolkata', state: 'West Bengal' },
  '700107': { area: 'Action Area', city: 'Kolkata', state: 'West Bengal' },
  '700135': { area: 'New Town Eco Park', city: 'Kolkata', state: 'West Bengal' },
  '700156': { area: 'Madhyamgram', city: 'Kolkata', state: 'West Bengal' },
  '711101': { area: 'Howrah', city: 'Howrah', state: 'West Bengal' },
  '711102': { area: 'Shibpur', city: 'Howrah', state: 'West Bengal' },
  '711106': { area: 'Santragachi', city: 'Howrah', state: 'West Bengal' },

  // Pune
  '411001': { area: 'Pune City', city: 'Pune', state: 'Maharashtra' },
  '411002': { area: 'Shivajinagar', city: 'Pune', state: 'Maharashtra' },
  '411003': { area: 'Deccan Gymkhana', city: 'Pune', state: 'Maharashtra' },
  '411004': { area: 'Erandwane', city: 'Pune', state: 'Maharashtra' },
  '411005': { area: 'Kothrud', city: 'Pune', state: 'Maharashtra' },
  '411006': { area: 'Aundh', city: 'Pune', state: 'Maharashtra' },
  '411007': { area: 'Pimpri', city: 'Pune', state: 'Maharashtra' },
  '411008': { area: 'Chinchwad', city: 'Pune', state: 'Maharashtra' },
  '411009': { area: 'Bibwewadi', city: 'Pune', state: 'Maharashtra' },
  '411011': { area: 'Hadapsar', city: 'Pune', state: 'Maharashtra' },
  '411013': { area: 'Camp', city: 'Pune', state: 'Maharashtra' },
  '411014': { area: 'Ghole Road', city: 'Pune', state: 'Maharashtra' },
  '411015': { area: 'Katraj', city: 'Pune', state: 'Maharashtra' },
  '411016': { area: 'Sinhagad Road', city: 'Pune', state: 'Maharashtra' },
  '411017': { area: 'Kondhwa', city: 'Pune', state: 'Maharashtra' },
  '411018': { area: 'Ambegaon', city: 'Pune', state: 'Maharashtra' },
  '411019': { area: 'Dhayari', city: 'Pune', state: 'Maharashtra' },
  '411020': { area: 'Narhe', city: 'Pune', state: 'Maharashtra' },
  '411021': { area: 'Bhosari', city: 'Pune', state: 'Maharashtra' },
  '411022': { area: 'Lohegaon', city: 'Pune', state: 'Maharashtra' },
  '411023': { area: 'Yerwada', city: 'Pune', state: 'Maharashtra' },
  '411028': { area: 'Wanowrie', city: 'Pune', state: 'Maharashtra' },
  '411030': { area: 'Manjri', city: 'Pune', state: 'Maharashtra' },
  '411033': { area: 'Dhanori', city: 'Pune', state: 'Maharashtra' },
  '411036': { area: 'Wakad', city: 'Pune', state: 'Maharashtra' },
  '411038': { area: 'Kothrud West', city: 'Pune', state: 'Maharashtra' },
  '411041': { area: 'Baner', city: 'Pune', state: 'Maharashtra' },
  '411044': { area: 'Magarpatta', city: 'Pune', state: 'Maharashtra' },
  '411045': { area: 'Balewadi', city: 'Pune', state: 'Maharashtra' },
  '411046': { area: 'Sus Road', city: 'Pune', state: 'Maharashtra' },
  '411048': { area: 'Wagholi', city: 'Pune', state: 'Maharashtra' },
  '411057': { area: 'Hinjewadi', city: 'Pune', state: 'Maharashtra' },
  '411060': { area: 'Undri', city: 'Pune', state: 'Maharashtra' },

  // Ahmedabad
  '380001': { area: 'Bhadra', city: 'Ahmedabad', state: 'Gujarat' },
  '380002': { area: 'Dudheshwar', city: 'Ahmedabad', state: 'Gujarat' },
  '380004': { area: 'Saraspur', city: 'Ahmedabad', state: 'Gujarat' },
  '380005': { area: 'Gomtipur', city: 'Ahmedabad', state: 'Gujarat' },
  '380006': { area: 'Raipur', city: 'Ahmedabad', state: 'Gujarat' },
  '380007': { area: 'Maninagar', city: 'Ahmedabad', state: 'Gujarat' },
  '380008': { area: 'Vatva', city: 'Ahmedabad', state: 'Gujarat' },
  '380009': { area: 'Navrangpura', city: 'Ahmedabad', state: 'Gujarat' },
  '380013': { area: 'Naranpura', city: 'Ahmedabad', state: 'Gujarat' },
  '380014': { area: 'Vastrapur', city: 'Ahmedabad', state: 'Gujarat' },
  '380015': { area: 'Satellite', city: 'Ahmedabad', state: 'Gujarat' },
  '380016': { area: 'Ghatlodia', city: 'Ahmedabad', state: 'Gujarat' },
  '380019': { area: 'Chandlodia', city: 'Ahmedabad', state: 'Gujarat' },
  '380021': { area: 'Naroda', city: 'Ahmedabad', state: 'Gujarat' },
  '380023': { area: 'Shahibaug', city: 'Ahmedabad', state: 'Gujarat' },
  '380024': { area: 'Ellis Bridge', city: 'Ahmedabad', state: 'Gujarat' },
  '380026': { area: 'Ambawadi', city: 'Ahmedabad', state: 'Gujarat' },
  '380027': { area: 'Thaltej', city: 'Ahmedabad', state: 'Gujarat' },
  '380051': { area: 'Bodakdev', city: 'Ahmedabad', state: 'Gujarat' },
  '380052': { area: 'Jodhpur', city: 'Ahmedabad', state: 'Gujarat' },
  '380054': { area: 'Prahlad Nagar', city: 'Ahmedabad', state: 'Gujarat' },
  '380058': { area: 'Bopal', city: 'Ahmedabad', state: 'Gujarat' },
  '380059': { area: 'Ghuma', city: 'Ahmedabad', state: 'Gujarat' },
  '380061': { area: 'Science City', city: 'Ahmedabad', state: 'Gujarat' },

  // Jaipur
  '302001': { area: 'Jaipur City', city: 'Jaipur', state: 'Rajasthan' },
  '302002': { area: 'Bani Park', city: 'Jaipur', state: 'Rajasthan' },
  '302003': { area: 'Chandpole', city: 'Jaipur', state: 'Rajasthan' },
  '302004': { area: 'Adarsh Nagar', city: 'Jaipur', state: 'Rajasthan' },
  '302005': { area: 'Civil Lines', city: 'Jaipur', state: 'Rajasthan' },
  '302006': { area: 'Vaishali Nagar', city: 'Jaipur', state: 'Rajasthan' },
  '302010': { area: 'Malviya Nagar', city: 'Jaipur', state: 'Rajasthan' },
  '302011': { area: 'Jagatpura', city: 'Jaipur', state: 'Rajasthan' },
  '302015': { area: 'Tonk Road', city: 'Jaipur', state: 'Rajasthan' },
  '302017': { area: 'Mansarovar', city: 'Jaipur', state: 'Rajasthan' },
  '302018': { area: 'Sanganer', city: 'Jaipur', state: 'Rajasthan' },
  '302019': { area: 'Sikar Road', city: 'Jaipur', state: 'Rajasthan' },
  '302020': { area: 'Sodala', city: 'Jaipur', state: 'Rajasthan' },
  '302021': { area: 'Shastri Nagar', city: 'Jaipur', state: 'Rajasthan' },
  '302022': { area: 'Pratap Nagar', city: 'Jaipur', state: 'Rajasthan' },
  '302029': { area: 'Vidhyadhar Nagar', city: 'Jaipur', state: 'Rajasthan' },
  '302031': { area: 'Sitapura', city: 'Jaipur', state: 'Rajasthan' },
  '302033': { area: 'Ajmer Road', city: 'Jaipur', state: 'Rajasthan' },

  // Noida & Gurgaon
  '201301': { area: 'Sector 18', city: 'Noida', state: 'Uttar Pradesh' },
  '201304': { area: 'Sector 62', city: 'Noida', state: 'Uttar Pradesh' },
  '201306': { area: 'Sector 137', city: 'Noida', state: 'Uttar Pradesh' },
  '201307': { area: 'Sector 150', city: 'Noida', state: 'Uttar Pradesh' },
  '201309': { area: 'Sector 168', city: 'Noida', state: 'Uttar Pradesh' },
  '201310': { area: 'Sector 16A', city: 'Noida', state: 'Uttar Pradesh' },
  '201313': { area: 'Sector 63', city: 'Noida', state: 'Uttar Pradesh' },
  '201316': { area: 'Greater Noida West', city: 'Greater Noida', state: 'Uttar Pradesh' },
  '201318': { area: 'Gaur City', city: 'Greater Noida', state: 'Uttar Pradesh' },
  '122001': { area: 'Gurgaon City', city: 'Gurgaon', state: 'Haryana' },
  '122002': { area: 'DLF Phase 1', city: 'Gurgaon', state: 'Haryana' },
  '122003': { area: 'Sector 14', city: 'Gurgaon', state: 'Haryana' },
  '122007': { area: 'Sushant Lok', city: 'Gurgaon', state: 'Haryana' },
  '122008': { area: 'Sector 56', city: 'Gurgaon', state: 'Haryana' },
  '122009': { area: 'Cyber City', city: 'Gurgaon', state: 'Haryana' },
  '122011': { area: 'Golf Course Road', city: 'Gurgaon', state: 'Haryana' },
  '122015': { area: 'Manesar', city: 'Gurgaon', state: 'Haryana' },
  '122016': { area: 'South City', city: 'Gurgaon', state: 'Haryana' },
  '122018': { area: 'Palam Vihar', city: 'Gurgaon', state: 'Haryana' },
  '122022': { area: 'New Gurgaon', city: 'Gurgaon', state: 'Haryana' },
}

export function lookupPincode(pin) {
  return PINCODES[pin] || null
}
